const Page = require('./helpers/page');

let page;

beforeEach(async () => {
    page = await Page.build();
    await page.goto('http://localhost:3000');
});

afterEach(async () => {
    // await broswer.close();
    await page.close();
});

test('the header has the correct text', async () => {
    const text = await page.getContentsOf('a.brand-logo');

    expect(text).toEqual('Blogster');
});

test('clicking login starts oauth flow', async () => {
    await page.click('.right a');

    const url = await page.url();
    expect(url).toMatch(/accounts\.google\.com/);
});

// CRAZY: Because it is difficult to go throught the CAPTCHA process
// we decide to simulate the login process by generate the session and session.sig
// ourselves. They are both be generated by cookieSession.

// test.only > in this file, only this test will be run
// test.only('...', () => {})
test('When signed in, shows logout button', async () => {
    await page.login();

    const text = await page.getContentsOf('a[href="/auth/logout"]');
    expect(text).toEqual('Logout');
});
